FROM gcc:4.9

WORKDIR /app

COPY C:/Users/ASUS/Desktop/online_judge/online_judge_4/src/main/java/com/spoj/online_judge/docker/code/code.cpp app/Main.cpp
COPY C:/Users/ASUS/Desktop/online_judge/online_judge_4/src/main/java/com/spoj/online_judge/docker/code/input.txt app/input.txt